groups:
  - name: microservices_alerts
    rules:
      # Alerta cuando un servicio está caído
      - alert: ServiceDown
        expr: up{job=~"orders-service|delivery-service"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Service {{ $labels.job }} is down"
          description: "Service {{ $labels.job }} has been down for more than 1 minute"

      # Alerta cuando el uso de memoria JVM es alto
      - alert: HighJVMMemoryUsage
        expr: (jvm_memory_used_bytes{job=~"orders-service|delivery-service", area="heap"} / jvm_memory_max_bytes{job=~"orders-service|delivery-service", area="heap"}) > 0.85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High JVM memory usage for {{ $labels.job }}"
          description: "JVM memory usage is above 85% for {{ $labels.job }}"

      # Alerta cuando hay muchos errores HTTP 5xx
      - alert: HighErrorRate
        expr: rate(http_server_requests_seconds_count{job=~"orders-service|delivery-service", status=~"5.."}[5m]) > 0.1
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High error rate for {{ $labels.job }}"
          description: "Error rate is above 0.1 errors/sec for {{ $labels.job }}"

      # Alerta cuando el tiempo de respuesta es alto
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_server_requests_seconds_bucket{job=~"orders-service|delivery-service"}[5m])) > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High response time for {{ $labels.job }}"
          description: "95th percentile response time is above 2 seconds for {{ $labels.job }}"

      # Alerta cuando hay muchos threads activos
      - alert: HighThreadCount
        expr: tomcat_threads_current_threads{job=~"orders-service|delivery-service"} > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High thread count for {{ $labels.job }}"
          description: "Thread count is above 80 for {{ $labels.job }}" 