global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Orders Service
  - job_name: 'orders-service'
    static_configs:
      - targets: ['orders-service:8084']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s

  # Delivery Service
  - job_name: 'delivery-service'
    static_configs:
      - targets: ['delivery-service:8083']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s

  # RedPanda
  - job_name: 'redpanda'
    static_configs:
      - targets: ['redpanda:9644']
    metrics_path: '/metrics'
    scrape_interval: 15s 